services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_OUTER_PORT}:5000"
    depends_on:
      - db
    volumes:
      - ./server:/app
    restart: on-failure
    networks:
      - bt-net

  db:
    image: postgres:15.5
    container_name: backend_db
    environment:
      - TZ=${TZ:-Europe/Moscow}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "${DB_OUTER_PORT}:5432"
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bt-net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:${CLIENT_INNER_PORT}"
    depends_on:
      - server
    restart: on-failure
    networks:
      - bt-net

networks:
  bt-net:
    name: bt-net
    driver: bridge

volumes:
  database: